version: '2'

services:
  mongodb_container:
    image: mongo:latest
    container_name: mongdb_container
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017