server:
  port: ${SERVER_PORT:8081}

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/axonmongo?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1111}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/axonframework

axon:
  serializer:
    general: jackson
    messages: jackson
    events: jackson
  eventhandling:
    processors:
      myProcessor2:
        mode: tracking
        thread-count: 4
        initial-segment-count: 4